# Generated by Django 5.0.6 on 2024-05-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='user',
            new_name='user_name',
        ),
    ]
