# Generated by Django 5.0.6 on 2024-05-19 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_rename_user_poste_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='user_name',
        ),
        migrations.AddField(
            model_name='poste',
            name='user',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='student_app.user'),
            preserve_default='True',
        ),
    ]
